### ISSUE TITLE
NL80211_CHANLIST_NOT_NL80211 in mac80211_get_chanlist not defined

### ISSUE THREAD

**Issue by michaelschratt** [kismetwireless/kismet#2]
Hi,

I face an error during compilation on Kali. The NL80211_CHANLIST_NOT_NL80211 variable has not been defined anywhere.

Best,
Michael

**Comment by kismetwireless** [comment]
Thanks - fixed in df583b5812d90e7aa1a372e817c8b546283c8365.

This also indicates you need to install, most likely, the libnl dev packages in kali; that code only gets compiled when you're missing libnl support.  Check the output from ./configure to see what's missing; on most modern systems you won't get too far without it (can't make monitor vifs, can't set HT channels, etc)
