### ISSUE TITLE
How to detect KRACK Attack on Kismet?

### ISSUE THREAD

**Issue by fachrurozyr99** [kismetwireless/kismet#363]
I've been configure the NONCEREUSE Alert in Kismet_alert.conf, But when i do some KRACK Attack to the target, there's no alert Show? 
The scenario is i set 3 devices, 1 as attacker, 1 as WIDS Kismet, and 1 as victim. But the WIDS can't detect the KRACK Attack from Attacker to victim.

Help me, thank you

**Comment by fachrurozyr99** [comment]
nobody can answer?

**Comment by kismetwireless** [comment]
Nonce reuse detection is only possible when 

a) you are on the proper channel at the proper time, 
b) you've seen the original exchange, and 
c) your device is capable of receiving all the packets required in the first place.

Handshakes are performed as data frames.  You will never see a handshake performed at a higher data rate than your hardware is capable of receiving in the first place, and you will miss any handshake happening while you are channel hopping to another channel.  All the normal warnings about missing data frames apply - 802.11n and faster can be extremely difficult to successfully capture data frames from due to mimo and related, chances of your capture card missing handshakes are very high.

It is to the best of my knowledge impossible to differentiate between a krack attack and a normal retransmission as a completely passive observer, which is why that alert is disabled by default.
