### ISSUE TITLE
compiling issue hanging up on make

### ISSUE THREAD

**Issue by icissel** [kismetwireless/kismet#407]
I have been trying to compile on an raspi with the most recent OS (debian v11 bullseye) and installed all of the dependencies, cloned, pulled and configured as indicated at https://www.kismetwireless.net/docs/readme/quickstart/ 
On make keeps hanging up with the following:
`pi@raspberrypi:~/kismet $ make
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c kis_external.cc -o kis_external.cc.o
In file included from /usr/include/c++/10/bits/stl_algobase.h:64,
                 from /usr/include/c++/10/memory:63,
                 from kis_external.cc:19:
/usr/include/c++/10/bits/stl_pair.h: In instantiation of ‘constexpr std::pair<typename std::__strip_reference_wrapper<typename std::decay<_Tp>::type>::__type, typename std::__strip_reference_wrapper<typename std::decay<_Tp2>::type>::__type> std::make_pair(_T1&&, _T2&&) [with _T1 = const double&; _T2 = const double&; typename std::__strip_reference_wrapper<typename std::decay<_Tp2>::type>::__type = double; typename std::__strip_reference_wrapper<typename std::decay<_Tp>::type>::__type = double]’:
trackedelement.h:1694:30:   required from ‘void tracker_element_core_pair<T1, T2, TT>::set(const T1&, const T2&) [with T1 = double; T2 = double; tracker_type TT = tracker_type::tracker_pair_double]’
trackedlocation.h:74:31:   required from here
/usr/include/c++/10/bits/stl_pair.h:567:5: note: parameter passing for argument of type ‘std::pair<double, double>’ when C++17 is enabled changed to match C++14 in GCC 10.1
  567 |     make_pair(_T1&& __x, _T2&& __y)
      |     ^~~~~~~~~`

**Comment by kismetwireless** [comment]
That looks like a warning from gcc (which is a whole other thing because it's not actually a useful message) rather than the actual error; it looks like you're trying to compile on a pi directly; that will likely be very difficult unless your pi has a LOT of ram.

Kismet does build fine in bullseye - the nightlies and releases are built in bullseye native containers - so my guess is that's one of gcc's spurious warnings, and the actual error is that it's running out of ram (or just taking forever - building native on a pi4 is still likely going to take you a few hours)

-m

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by icissel** [comment]
Excellent thank you!!  Much smoother with the package.
