### ISSUE TITLE
Kismet Server Freeze

### ISSUE THREAD

**Issue by marcotuna** [kismetwireless/kismet#53]
Hello, I have setup a Kismet Server and I have currently one node sending data to it (remotely) however the Kismet server keeps freezing, in the shell it stops responding and in the web panel as well, I've already tried on two different servers with 8 GB of RAM the only thing that is equal on both is the Operating System which is Debian 9.4, however one is inside a LXC Container with Ubuntu 16.04.
The RAM and CPU usage are low.
What kind of information should I provide in order to diagnose this problem?
I have also persistent_state=true however I cannot start the server because it is on loop:
"Devicetracker tried to add device XXX which already exists"
If I disable the server starts

**Comment by kismetwireless** [comment]
persistent_state is currently disabled by default, because it seems that it has some issues; I wouldn't recommend enabling it.

Make sure you're on the latest git code (fixes went in last week and this week for some thread stalls); there's debug instructions in the README for configuring GDB and getting a dump of all the state in Kismet, if you can post the output of that.
